### ISSUE TITLE
Add TorBirdy

### ISSUE THREAD

**Issue by mpmks11** [freedomofpress/encryption-works#24]
What about recommending TorBirdy for email anonymization. I like it, but find it very hard to install. I think it would be very beneficial to give a step-by-step guide on how to install it.

**Comment by garrettr** [comment]
TorBirdy is mentioned in the latest draft of Encryption Works because it is the only way that we know of to enable the use of `gpg --hidden-recipient` without using the command line.

It is not a step-by-step guide, but we are trying to keep Encryption Works as more an outline and set of recommendations rather than a set of step-by-step guides. If you know of any good guides for installing and using TorBirdy, we would be happy to link to them from Encryption Works.
