### ISSUE TITLE
Update mention of TrueCrypt.

### ISSUE THREAD

**Issue by jdgalt** [freedomofpress/encryption-works#25]
TrueCrypt was (effectively) taken offline by its developers in May 2014.  The sites truecrypt.org and truecrypt.sourceforge.net still exist, but all you can obtain there is a "crippled" version of the program, version 7.2, which is identical to the last "real" version, 7.1a, except that they've disabled the creation of new TrueCrypt volumes.

The only explanation given is that Windows Vista (and later versions) offer volume encryption of their own.  But as your document (and ssd.eff.org) point out, Microsoft is known to put NSA backdoors in its products, so that's not a reasonable alternative even for Windows users, and of course the Mac and Linux users who rely on TC don't have that as an option anyway.

I would like to see this product resurrected under new ownership.  And I have copies of TrueCrypt 7.1a, both binary and source, and am willing to share them.  But unless that happens I'm afraid we'll have to refer to TrueCrypt in the past tense.

**Comment by garrettr** [comment]
The [latest draft](https://github.com/freedomofpress/encryption-works/blob/de77f2b8750e90f79aaa512d02940d297c4838b3/encryption_works.md) of Encryption Works no longer mentions TrueCrypt. We are as confused and uncertain as anybody else as to what tool to recommend for cross-platform volume encryption, and would appreciate any and all recommendations!

In the meantime, I consider this issue to be resolved because we no longer even mention TrueCrypt.
