### ISSUE TITLE
Clarify where new issue is being made

### ISSUE THREAD

**Issue by RichardLitt** [freedomofpress/encryption-works#33]
> Warning: This guide has not updated in over a year. Freedom of the Press Foundation is working on an updated version. If you're interested in contributing, or have ideas for what this guide should cover, please submit issues on GitHub

Is this being edited // written somewhere? How can people contribute actively - do you need help writing it, or should we just point out errors // add suggestions here?

**Comment by conorsch** [comment]
See also #15, which discusses using annotation frameworks rather than GitHub Issues for managing edits. My opinion is that GitHub Issues are the lowest barrier to entry, accounting for effort by all sides, including development and maintenance of a less out-of-the-box solution than GitHub.

Even if we stick with using Issues, we may wish to add a [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) to document the recommended workflow for contributors.

**Comment by RichardLitt** [comment]
Yes, I'm in that issue (unless you were talking to the issue audience at large, in which case, cool). I think that GitHub is a good place to comment - it's just not clear to me where changes are being made, as the warning above says it is an updated version is in the works. 

Adding a CONTRIBUTING.md would be fantastic. There might be a good templates [here](https://github.com/contribute-md/contribute-md-template). If not, I'm happy to see what I can make.

**Comment by conorsch** [comment]
@RichardLitt Yes, mention of #15 was to general community, as follow-up to our discussion there. Great to hear you agree on the CONTRIBUTING.md idea. Advantages as I see them:

* honors established GitHub/FOSS pragma
* obvious to beginners because it's presented on the mainpage of the repo in the files view
* condenses discussion of suggested workflow scattered among issues into a single document that can be updated

So, low barrier to entry *and* future-compatible. So far, items that should be included:

* use GitHub issues for discussion
* submit edits via GitHub PRs (makes review of specific changes much easier, and keeps authorship transparent)
* formatting guidelines (e.g. column width, so markdown is readable unwrapped)
* general git learning materials? 
* general markdown learning materials?

If you have more ideas about what the CONTRIBUTING doc should include, holler.

**Comment by harlo** [comment]
It would be cool if we hooked up [the hosted version](https://freedom.press/encryption-works) to Genius via its API.  Would it even be possible to use the Genius API and Github's webhooks together to convert legitimate annotations into issues onto the repo?

**Comment by conorsch** [comment]
For those not familiar, [Genius provides an API for web annotations](https://docs.genius.com/#annotations-h2). At a glance, wiring up integration for the hosted version is more effort than it's worth. The existing hosted version already links prominently to this repo, and #53 (among others) makes contributing guidelines much clearer.

In general, annotation frameworks strive to make the open web *more like open source git-managed projects*, so I think we're ahead of the game by hosting on git already. Yes, there is an assumption of technical literacy in using git for editing prose, but in the context of a document like **Encryption Works**, I don't find such an assumption untenable.
