### ISSUE TITLE
Clarify intended audience and level of technical proficiency

### ISSUE THREAD

**Issue by runasand** [freedomofpress/encryption-works#9]
The guide is technically sound, but it is unclear who the target audience is and what level of technical proficiency is expected. Do we want to target journalists with some existing knowledge of digital security tools and threat models or a more general audience?

**Comment by fowlslegs** [comment]
I think as it is this guide has something to offer both to complete beginners and those with some basic knowledge of digital security tools--journalist or otherwise. This is an old issue and since I think the document itself answers this question, I'm going to close it. Feel free to re-open if you believe some parts of it are targeted towards too advanced of users.
